### ISSUE TITLE
 add some sort of toast while stuff is downloading, flashing, etc.

### ISSUE THREAD

**Issue by River-Mochi** [Spagett1/PineFlash#11]
- [ ] add some sort of toast while stuff is downloading, flashing, etc.

moving this stuff out of Readme page and into actionable issue tickets.

**Comment by Spagett1** [comment]
Good idea, im going to close this issue though because that has already been added a while back.

**Comment by River-Mochi** [comment]
why did you close this  :)  idea was keep it open until it's done.  I basically copied this straight from your   TODO list
