### ISSUE TITLE
extra packages needed for arm build.

### ISSUE THREAD

**Issue by River-Mochi** [Spagett1/PineFlash#18]
- oko_123  reported he had to install  additional dependencies to get it to build on his  arm.  and he got it to work, he showed screenshots. 
- This is the working Binary he made  and asked me to give you:  https://sf.wooof.fun/f/eb82448df2af4e60a085/
- he built the binary  using "an Oracle Ampere VM (ARM) with Ubuntu"
- Ubuntu list is  packages he installed
- he used Manual build method 2, and not the script.
- right side was his guesses for  what I might need to use on Arch manjaro, but we could not find all the exact matches.

```
**Ubuntu/Debian derivatives**      **Arch based possible same package?**
g++                                   |     gcc
pkg-config                            |     pkgconf
libglib2.0-dev                        |     glibc 
build-essential                       |     base-devel
libfontconfig-dev                     |     fontconfig
fontconfig-config                     |     (nothing exist?)
libgdk3.0-cli-dev                     |      ??  
libatk1.0-0                           |     atkmm
libatk1.0-dev                         |     libatk1.0-dev  
libgtk-3-dev                          |     gtk3
```

I found  "atkmm-2.36" which  I installed on manjaro because I could not find the "libgdk3.0-cli-dev"  he installed and I figured it wouldn't hurt.

**Comment by River-Mochi** [comment]
if the Dependency list gets too long, you could use a  2 column table for it.

**Comment by Spagett1** [comment]
Ive added em in, from now on all dependancy lists will be in a drop down menu for that distro.
