### ISSUE TITLE
Bug: environment path is set to C:   in windows 11,  causes PineFlash to crash

### ISSUE THREAD

**Issue by River-Mochi** [Spagett1/PineFlash#23]
- Installed 2 times,  it auto  sets path to `C:  `  only . 
- this causes  Pineflash to crash when "Update" button is pressed because  it can't find the Blisp for V2 or DFU for V1.
-  manually  setting path  environment  variable  fixes this.  It must have a path to `tools ` folder. 
    `C:\Program Files (x86)\PineFlash\tools`
<br>

![image](https://user-images.githubusercontent.com/97197236/230348665-2ea10732-2f72-425c-bdec-e9e2d2bbcdee.png)

**Comment by Spagett1** [comment]
This is solved as pineflash now doesnt use the path on windows for anything, problem solved.
