### ISSUE TITLE
add method that detects if   pinecil is connected to PC

### ISSUE THREAD

**Issue by River-Mochi** [Spagett1/PineFlash#25]
### Add a method that detects if pinecil is connected to the PC.
Then do some change in the app to indicate this.
For example in the  pine64_updater gui  from Gamiee: 
  if you  do not have the Pinecil connected  (I assume it checks dmsg or other)  then it shows a photo of what you need to do to connect to PC.   that Photo does not go away and enter the next screen to update until you properly connect. 

This helps a lot when volunteers are remotely helping someone who can not install.  We have an indicator and can ask them if they are seeing the photo showing you how to connect?  Then we know you are not connected to the PC,  try a different cable or port.

**Additional Info:**
V1 and V2  connect differently  to the PC.

**V2** -    on Linux, it will connect as a serial ttyACM USB ACM type device.   
 In windows, it connects as a  Serial **COM** device in Device Manager. It connects to a random COM port that is available, while it is "3"  here, it could be 5 or 6.
<br>

![image](https://user-images.githubusercontent.com/97197236/230481155-76debc61-3800-4742-acec-f9f4f41bfa6a.png)

### V1  below: on windows, it will show up as an "Unknown device"  under Universal Serial Bus devices.

Pinecil will not show up as usb-c storage flash drive device like some other irons. This is not supported by IronOS.
<br>

![image](https://user-images.githubusercontent.com/97197236/230479909-7fe81d24-b0f2-43e8-8363-8a27a2d09187.png)

**Comment by Spagett1** [comment]
Ok ive added this feature to the master branch. Ill probably improve it in the future with a little image or some text but right now but as it is functional and will mot update if not plugged in (button is greyed out) its good enough for now.
