### ISSUE TITLE
can't install with deb package on Pop!_OS 22.04 LTS

### ISSUE THREAD

**Issue by LokiMetaSmith** [Spagett1/PineFlash#37]
The following packages have unmet dependencies:
 pineflash : Depends: polkit but it is not installable
E: Unable to correct problems, you have held broken packages.

polkitd is installed, so not sure why it's an unmet dependency.

**Comment by LokiMetaSmith** [comment]
Ubuntu doesn't list polkit  
https://packages.ubuntu.com/search?keywords=polkit&searchon=names&suite=kinetic&section=all

**Comment by Spagett1** [comment]
Thanks for letting me know, is probably got a different package name, I'll update it soon

**Comment by Spagett1** [comment]
I think libpolkit-agent-1-0 is the right package. Ill update that so the next release uses the correct version. Until that goes through you can use the generic tarball as it doesn't handle deps..

**Comment by ValeriyDP** [comment]
Ubuntu 20.04 problem still here 
![image](https://github.com/Spagett1/PineFlash/assets/11663800/26f0180d-b5a5-4131-91c5-d55a2ffa08e0)

**Comment by makergamer** [comment]
Working on updating a Pinecil v1.

Mint 21 (Vanessa) has this identical message. polkitd & libpolkit-agent-1-0 are all current with v0.105-33 . `sudo dpkg -i ./pineflash_0.5.0_amd64.deb` refused to install by throwing the polkit missing.

Determined to make it work, I downloaded the pineflash_0.5.0_amd64.tar.xz . Running it as myself, everything works until it asks for my password for sudo, then it fails. The GUI stayed up, but threw a message it failed to flash.

If I `sudo ./pineflash` , it launches but after selecting the Pinecil v1, it crashes. (edit forthcoming from the other laptop. gotta relog.)

**Comment by Spagett1** [comment]
This should be fixed now, if the problems persist feel free to reopen the issue
