### ISSUE TITLE
`PKGBUILD`: Wrong maintainer given.

### ISSUE THREAD

**Issue by dreirund** [Spagett1/PineFlash#39]
Ahoj,

I see that you have included an [Arch Linux `PKGBUILD` in your source repository](https://github.com/Spagett1/PineFlash/blob/master/PKGBUILD).

On the one hand, you cite the Arch Linux AUR user "dreieck" as maintainer of the `PKGBUILD`. On the other hand, you have modified that `PKGBUILD` from the one you seem to have taken from the AUR.

Please correct the `Maintainer:`-line in the `PKGBUILD` to yourself.

Regards!

**Comment by Spagett1** [comment]
Hey, since I've updated the readme to just get the user to use the aur and removed the pkgbuild this is solved, thanks.
