### ISSUE TITLE
Arch Linux dependencies: Please differentiate makedependencies and runtime dependencies, and please clarify `atmm`.

### ISSUE THREAD

**Issue by dreirund** [Spagett1/PineFlash#40]
Ahoj,

in yout [`README.md`](https://github.com/Spagett1/PineFlash/blob/master/README.md) you mention dependencies for Arch Linux.

Please differentiate between dependencies needed only to build the software and dependencies needed at runtime.

Also, you specify that `atmm` is a dependency. But there is no Arch Linux package `atmm`, and the software build fine without it. Can you check which dependency you really mean and correct the `README.md`?

Regards!

**Comment by Spagett1** [comment]
Hey, i think atmm was a mistake by me putting it in on arch as whatever it provides on debian (where i think i found the need for it) is provided by some dependancy of other dependancies so its not needed. Thanks for letting me know, ive updated the readme.

Regards!
