### ISSUE TITLE
`PKGBUILD`: several issues; link to AUR instead of including here.

### ISSUE THREAD

**Issue by dreirund** [Spagett1/PineFlash#41]
Ahoj,

I see that you have included an [Arch Linux `PKGBUILD` in your source repository](https://github.com/Spagett1/PineFlash/blob/master/PKGBUILD).

That `PKGBUILD` is not complete, e.g. the package `cargo-ndk` is needed as a make dependency, see [this comment](https://aur.archlinux.org/packages/pineflash-git#comment-911951).

Also, your repository now has official version numbers (which can be obtained by parsing `git describe --tags`), but you still obtain the version in `pkgver()` by parsing the very same `PKGBUILD`'s `$pkgver`, thus having a kind of circle argument.

Also, `blisp` is part of the Arch Linux repositories. You do not need to build it yourself. Just add `blisp` to the `depends` array, or add `optdepends=('blisp: For pinecil V2 support (needs to be present during package build)')`.  
If you really insist to build and install blisp by yourself: Since you install `/usr/bin/blisp`, you need to add `blisp` to the `conflicts` and `provides` arrays.

I recommend to remove the `PKGBUILD` from your repository and link to the [AUR package `pineflash-git`](https://aur.archlinux.org/packages/pineflash-git), where the up to datee `PKGBUILD` should be found and issues regarding the `PKGBUILD` can be posted.

The AUR package `pineflash-git` has gotten an overhaul.

Regards!

**Comment by Spagett1** [comment]
Thanks for letting me know, ive switched away from arch to a rhel based distro so ive sorta fallen behind on maintaining the PKGBUILD, thanks for letting me know the aur one has gotten an overhaull as last time i checked it a few things where broken. I'll remove the one in this repo shortly.
