### ISSUE TITLE
Unable to build on macOS

### ISSUE THREAD

**Issue by natecox** [Spagett1/PineFlash#43]
On a fresh clone of the repo running the installer gives me the following:

```
❯ sh generic_unix_install.sh
generic_unix_install.sh: line 8: cargo: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  100k  100  100k    0     0   107k      0 --:--:-- --:--:-- --:--:--  322k
Archive:  blisp-macos64-v0.0.3.zip
replace blisp? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: blisp                   
cp: ./target/release/pineflash: No such file or directory
```

Running on a 13-inch 2020 MacBook Pro, Ventura 13.3.1

**Comment by Spagett1** [comment]
Hi, the installer doent handle dependancies, you will need to install rust first. go to [rustup.rs](https://rustup.rs/)

**Comment by natecox** [comment]
Hmm, this probably warrants further discussion around command output. I didn’t notice the cargo not found error because it continued with trying to install blisp. Stopping execution on the first error would make that a lot clearer.

**Comment by Spagett1** [comment]
Today's not a bad idea.

**Comment by noestreich** [comment]
[pineflash.zip](https://github.com/Spagett1/PineFlash/files/11520142/pineflash.zip)
Just compiled it on an 64bit Intel iMac from 2019 and attached the binary, i had hoped to find somewhere in the discussions. Runs just fine. 


![pinescreen](https://github.com/Spagett1/PineFlash/assets/309419/6e320816-b028-49ea-87c1-c8e52c10610b)

**Comment by shadowpanther** [comment]
While compiling the binary, I get the following:
```
error[E0425]: cannot find value `blisp_version` in this scope
   --> src/submodules/main_panel.rs:126:55
    |
126 | ...                   let ver = blisp_version.split("\n");
    |                                 ^^^^^^^^^^^^^ not found in this scope

warning: unused import: `std::process::Command`
  --> src/submodules/main_panel.rs:19:5
   |
19 | use std::process::Command;
   |     ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

For more information about this error, try `rustc --explain E0425`.
warning: `pineflash` (bin "pineflash") generated 1 warning
error: could not compile `pineflash` (bin "pineflash") due to previous error; 1 warning emitted
```

It's my first time seeing Rust, but I see only branches for `linux` and `windows` in `src/submodules/main_panel.rs`

**Comment by Spagett1** [comment]
Hey, thanks for reporting the bug, your correct I completely forgot about macos when writing that part. I've updated it now so if you pull the latest master branch it should compile

**Comment by shadowpanther** [comment]
Thanks, it does compile now. The dock icon is just a pink square, but at least it launches.

**Comment by Spagett1** [comment]
Cool, yeah the macos support is extremely basic right now unfortunately because I don't have a Mac to actually test on. I really do need to get around to having a proper macos release package so it doesn't need to be compiled

**Comment by Spagett1** [comment]
The original problem seems to be fixed so I'll close up this issue now.
