### ISSUE TITLE
Windows 10 x64 fails to open pineflash

### ISSUE THREAD

**Issue by SeafoodSauce** [Spagett1/PineFlash#48]
Hello spagett1 
Recently got my pinecel v2 used latest version pinecell  0.5 on Windows 10 x64,program installs no issues. Upon starting pineflash the program doesn't open at all. 
The Desktop shortcut and inside program files pineflash directory pineflash.
Doesn't even show under Windows task manager as running or launched

**Comment by Spagett1** [comment]
Gday, i think this is likely related to other issues on other os's, does it happen with the latest release?

**Comment by SeafoodSauce** [comment]
Hello mate 
Yeah tried latest version just now installs perfectly still doesn't open the app at all 🤔

**Comment by Spagett1** [comment]
Righto, the issue hasn't occurred to me when I tested it on windows but I'll borrow some other machines and see if I can recreate it.

**Comment by VasokDron** [comment]
There was such a problem, I solved it by updating the video driver, the standard one from Microsoft was to blame for everything.

**Comment by Spagett1** [comment]
Great to know! Thanks I'll close the issue then.
