### ISSUE TITLE
pineflash installation issue Linux Mint 21.1 x86_64

### ISSUE THREAD

**Issue by AdrianEdelen** [Spagett1/PineFlash#49]
Issue:
unable to properly install Pineflash with apt.
`sudo apt install ./pineflash_*_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'pineflash' instead of './pineflash_0.5.0_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pineflash : Depends: polkit but it is not installable
E: Unable to correct problems, you have held broken packages.
`

to reproduce:

download deb package from releases
attempt install via apt

expected behavior:

the package install properly

I believe that the issue may arrive from the polkit / policykit-1 naming discrepancy.

**Comment by AdrianEdelen** [comment]
I repackaged the deb file and changed the dependency to 'policykit-1' and it seems to be working.

**Comment by Spagett1** [comment]
Hey, yeah sorry I got the dep name wrong for debian based distros, I've fixed it in the master branch, it just hasn't made it to the releases yet

**Comment by Spagett1** [comment]
I should probably push a release for this

**Comment by ItchyBugReporter** [comment]
The polkit dependency is also an issue on Devuan 4.x "Chimaera", which is a derivative of Debian 11.x "Bullseye".

**Comment by Spagett1** [comment]
should be all fixed in the latest release
