### ISSUE TITLE
Build failing because a dependency isn't downloadable.

### ISSUE THREAD

**Issue by Janik-Haag** [Spagett1/PineFlash#51]
I'm trying to build PineFlash but it failes because some dep can't be verified anymore:
```
error: failed to sync

Caused by:
  failed to download packages

Caused by:
  failed to download replaced source registry `crates-io`

Caused by:
  failed to verify the checksum of `ndk-sys v0.4.0`
```

**Comment by Elara6331** [comment]
This seems to be caused by rust-lang/cargo#11412. Alacritty fixed this by [updating ndk-sys](https://github.com/alacritty/alacritty/commit/3354203e571e427b7152999d13af8a1cbd14e0d8)

**Comment by Spagett1** [comment]
Interesting, ill try adding the same thing alacritty did. as long as it compiles properly ill push the change and hopefully that solves the error. ndk-sys is being pulled in by a dependancy so fingers crossed nothing breaks cause of it.

**Comment by MarijnS95** [comment]
Updating/regenerating the lock file with `ndk-sys 0.4.1` should solve this, sorry again for the noise :disappointed:.

**Comment by Spagett1** [comment]
Great, glad it's fixed!  I'll close up the issue now
