### ISSUE TITLE
Pineflash missing libraries on Fedora 38

### ISSUE THREAD

**Issue by TheGamerCanine** [Spagett1/PineFlash#54]
The program installs just fine from the provided rpm package, but won't open. If I try to open it from the command line I get the following:
`pineflash: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory`

**Comment by Spagett1** [comment]
A quick google shows bzip2-libs needs to be installed, I'll add it to the next release but you can install is manually

**Comment by Spagett1** [comment]
Just curious aswell, are you on server or workstation? I assume that the reason no-one else has reported this is that they already have it installed. Thanks for reporting the issue.

**Comment by TheGamerCanine** [comment]
I'm on workstation and bzip2-libs is installed, I made sure before sending the report.

**Comment by Spagett1** [comment]
do you have bzip2-devel? that may be needed aswell

**Comment by Driiaax** [comment]
Hello, I am also on Fedora 38 workstation with the same problem. Confirmed that bzip2-libs is installed and added bzip2-devel as well but still get the same results. Fortunately the AppImage works so thanks for that.

**Comment by Spagett1** [comment]
Gday, yeah canine and I spent some time trying to fix the issue but unfortunately we couldn't solve the issue.

This is why once I am certain the appimage has no downsides to the native packages (which I think is already the case) and I figure out how to build a flatpak, I plan on removing the distro specific packaging.

**Comment by Driiaax** [comment]
Sounds good. Bless Flatpaks. Regardless, the AppImage worked flawlessly. 👍

**Comment by Spagett1** [comment]
Glad to hear the appimage is working well :)
