### ISSUE TITLE
Include blisp and other dependencies in packages

### ISSUE THREAD

**Issue by qwertychouskie** [Spagett1/PineFlash#59]
Only the AppImage includes `blisp` and such, but the AppImage isn't working for me (https://github.com/Spagett1/PineFlash/issues/46#issuecomment-1642902095).  It would be good to include these in the normal packages.

**Comment by Spagett1** [comment]
This has been solved with the latest release 👍

**Comment by qwertychouskie** [comment]
This was fixed for the deb and rpm packages, but `pineflash-0.5.3-1-x86_64.pkg.tar.zst` still doesn't include `blisp`.
