### ISSUE TITLE
PineFlash AppImage not running on Void Linux

### ISSUE THREAD

**Issue by Le0xFF** [Spagett1/PineFlash#64]
Hi and thank you so much for your work!

I was trying to run the latest version of the AppImage on VoidLinux but sadly it didn't start due to the following error:
```
error while loading shared libraries: __vdso_gettimeofday: invalid mode for dlopen(): Invalid argument
```
Any idea regarding the issue?

---

I also tried directly the `.deb` version and it did run without any issues, only a small "warning" regarding `libcurl` (that is installed in the system) but I don't think that's a problem, since the download and the flashing went absolutely fine.
``` sh
$ pineflash
pineflash: /usr/lib/libcurl.so.4: no version information available (required by pineflash)

$ ls -la /usr/lib/libcurl.so.4
lrwxrwxrwx 1 root root 16 14 set 06.23 /usr/lib/libcurl.so.4 -> libcurl.so.4.8.0
```

**Comment by Spagett1** [comment]
Hi, are you running void musl? All the binaries of pineflash are built against glibc (this includes the appimage)

**Comment by Le0xFF** [comment]
No, I'm running the glibc version of Void! If it can help, here's the glibc version:
``` sh
$ ldd --version
ldd (GNU libc) 2.36
```

**Comment by Spagett1** [comment]
Oh righto.

I'm on version 2.38, i assume it's probably some kind of version mismatch

**Comment by Le0xFF** [comment]
Oh, bummer, I guess I have to wait for my distro maintainer to update that.
Luckily, as I said, the `.deb` version works so not a big deal.
Thank you again!

**Comment by Spagett1** [comment]
Glad that the deb works for you. I think the deb version works as I build it against debians version of glibc (which being debian is likely ancient haha). Glad it works, I may consider a void package in the future (not only cause of glibc versioning but also so there is a musl version out there for people who use that) but that depends on a couple factors including how much time I have which is pretty limited at the moment.

**Comment by Le0xFF** [comment]
A dedicated Void package would be awesome, but of course, take you time!
I think Void is like the perfect distro for us tinkerers 😄

**Comment by Spagett1** [comment]
Haha, I use artix at the moment but I'd be lying if I said void has never intrigued me.
