### ISSUE TITLE
Blisp: SP open failed: -2

### ISSUE THREAD

**Issue by saibhusain** [Spagett1/pineflash#65]
This might be a simple problem, but I haven't found any older threads about it. Pinecil V2 connects just fine, but flashing fails with the following logs:

Pineflash v0.5.3 Windows
PineFlash: Versions successfully fetched.
Pineflash: Pinecilv2 detected
PineFlash: Serial port is COM5 
PineFlash: Download of Language Info Complete.
PineFlash: Downloading Firmware Pinecilv2 v2.22-rc2.
PineFlash: Download Complete.
PineFlash: File extracted successfully
PineFlash: Attempting to flash Pinecilv2 with the firmware C:\Users\...
Blisp: SP open failed: -2
Failed to open device.

**Comment by 1jgj90g2nk** [comment]
Problems with flashing can happen if the pinecil tip is still inserted. Make sure you remove the tip off your device before connecting it to your computer. Hope it helps!

**Comment by sloboy** [comment]
I have the same issue as above, even with tip removed.

**Comment by Spagett1** [comment]
This seems to be an issue with the upstream blisp so I'm closing the issue, I'd suggest reporting it there.
