### ISSUE TITLE
[Bug] very small window

### ISSUE THREAD

**Issue by Soma-Schicksal** [Spagett1/PineFlash#9]
On manjaro KDE 5.26 I was not able to use the gui because most of the stuff weren't shown couldn't move or resize the window as well.

![Screenshot_20230321_095745](https://user-images.githubusercontent.com/128456551/226548758-817a0274-1f4d-4cf9-bd84-31ef19755db9.png)

the workaround is tiling mode just forced it to one side (Start button+right) and it became usable again.

**Comment by Spagett1** [comment]
thanks, ill have to investigate this.

**Comment by Spagett1** [comment]
Ive fixed the issue in the main branch, if you rebuild straight from git or update the aur package it should be solved. If it doesn't work then don't hesitate to reopen the issue if somethings gone wrong.
